# Starter pipeline
# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: SelfHostedPool  # Specify the name of your agent pool
  #vmImage: ubuntu-latest

jobs:
- job: Build
  steps:
  - checkout: self
    path: pipelines-java

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: x64
      jdkSourceOption: LocalDirectory
      #jdkFile: "/applications/builds/openlogic-openjdk-21.0.6+7-linux-x64.tar.gz"
      jdkFile: "/applications/builds/openjdk-11.0.0.2_linux-x64.tar.gz"
      jdkDestinationDirectory: "/applications/builds/binaries/externals"
      cleanDestinationDirectory: true
  - task: Maven@3
    inputs:
      mavenPomFile: 'pipelines-java/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      #jdkSourceOption: 'PreInstalled' 
      jdkSourceOption: LocalDirectory
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
